# Volume
UP                  add volume 5
DOWN                add volume -5
w                   add volume 5
s                   add volume -5
m                   cycle mute

# Subtitles
Ctrl+LEFT           add sub-delay -0.1
Ctrl+RIGHT          add sub-delay 0.1
Ctrl+a              add sub-delay -0.1
Ctrl+d              add sub-delay 0.1

# Seek
LEFT                seek -5 exact
RIGHT               seek 5 exact
Shift+LEFT          seek -1 exact
Shift+RIGHT         seek 1 exact
Ctrl+Shift+LEFT     seek -30
Ctrl+Shift+RIGHT    seek 30
a                   seek -5 exact
d                   seek 5 exact
A                   seek -1 exact
D                   seek 1 exact
Ctrl+A              seek -30
Ctrl+D              seek 30

# System
f                   cycle fullscreen
q                   quit

# Mouse buttons
MBTN_LEFT           cycle pause
MBTN_RIGHT          script-binding select/menu

# Disabled keys
9                   ignore
0                   ignore

